"""Add user roles to user model

Revision ID: 8ae801e3943b
Revises: 1e5903b0048c
Create Date: 2025-12-30 00:38:39.417152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae801e3943b'
down_revision = '1e5903b0048c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    userrole_enum = sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Add column with enum type
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True, server_default='USER'))
    
    # Set default value for existing users
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")
    
    # Make column non-nullable
    op.alter_column('users', 'role', nullable=False)
    
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'role')
    # Drop enum type
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

