"""Add notification enhancements: priority, type, metadata, relationships

Revision ID: 8fa329bdcc3c
Revises: initial001
Create Date: 2025-12-29 23:49:05.691284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa329bdcc3c'
down_revision = 'initial001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('businesses_ein_key'), 'businesses', type_='unique')
    op.drop_index(op.f('ix_businesses_ein'), table_name='businesses')
    op.create_index(op.f('ix_businesses_ein'), 'businesses', ['ein'], unique=True)
    
    # Add new columns to notifications table
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=True, server_default='medium'))
    op.add_column('notifications', sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('notifications', sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('notifications', sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('notifications', sa.Column('notification_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('notifications', sa.Column('email_sent', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('notifications', sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing records: copy notification_type to type, read to is_read
    op.execute("""
        UPDATE notifications 
        SET type = notification_type,
            is_read = read,
            priority = 'medium'
        WHERE type IS NULL
    """)
    
    # Make columns NOT NULL after data migration
    op.alter_column('notifications', 'type', nullable=False)
    op.alter_column('notifications', 'priority', nullable=False, server_default='medium')
    op.alter_column('notifications', 'is_read', nullable=False, server_default='false')
    op.alter_column('notifications', 'email_sent', nullable=False, server_default='false')
    
    # Create index and foreign keys
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_foreign_key('fk_notifications_order_id', 'notifications', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('fk_notifications_ticket_id', 'notifications', 'support_tickets', ['ticket_id'], ['id'])
    op.create_foreign_key('fk_notifications_document_id', 'notifications', 'documents', ['document_id'], ['id'])
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.drop_constraint(op.f('support_tickets_ticket_number_key'), 'support_tickets', type_='unique')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=False)
    op.create_unique_constraint(op.f('support_tickets_ticket_number_key'), 'support_tickets', ['ticket_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('fk_notifications_document_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_ticket_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_order_id', 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_column('notifications', 'email_sent_at')
    op.drop_column('notifications', 'email_sent')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'notification_metadata')
    op.drop_column('notifications', 'ticket_id')
    op.drop_column('notifications', 'document_id')
    op.drop_column('notifications', 'order_id')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'type')
    op.drop_index(op.f('ix_businesses_ein'), table_name='businesses')
    op.create_index(op.f('ix_businesses_ein'), 'businesses', ['ein'], unique=False)
    op.create_unique_constraint(op.f('businesses_ein_key'), 'businesses', ['ein'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

