"""add_audit_logs_table

Revision ID: a2e5c9fdecb4
Revises: 8ae801e3943b
Create Date: 2025-12-30 15:03:56.867382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2e5c9fdecb4'
down_revision = '8ae801e3943b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'USER'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'USER'::userrole"))
    # ### end Alembic commands ###

