"""Add onboarding fields to user model

Revision ID: e552dcbfa3e6
Revises: 8fa329bdcc3c
Create Date: 2025-12-30 00:08:32.297119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e552dcbfa3e6'
down_revision = '8fa329bdcc3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET onboarding_completed = FALSE WHERE onboarding_completed IS NULL")
    
    # Make onboarding_completed NOT NULL with default
    op.alter_column('users', 'onboarding_completed',
                   existing_type=sa.Boolean(),
                   nullable=False,
                   server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'onboarding_completed')
    op.alter_column('notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###

